{
 "title": "Transactions",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Daily Spending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "financial_data",
     "rawSql": "SELECT                                                                   \n  $__timeGroupAlias(alert_datetime, 1d),                                 \n  SUM(amount) AS \"Daily Spend\"                                           \nFROM silver.transactions                                                 \nWHERE transaction_type = 'PURCHASE'                                      \n  AND $__timeFilter(alert_datetime)                                      \nGROUP BY 1                                       \nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Top 5 Spent by Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "financial_data",
     "rawSql": "SELECT\n  vendor_classification AS \"Category\",\n  SUM(amount) AS \"Total Spend\"\nFROM silver.transactions\nWHERE transaction_type = 'PURCHASE'\n  AND $__timeFilter(alert_datetime)\nGROUP BY vendor_classification\nORDER BY \"Total Spend\" DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Recent Transactions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "dataset": "financial_data",
     "rawSql": "SELECT alert_datetime AS \"time\", vendor, amount, vendor_classification AS \"category\", confidence_score AS \"confidence\" FROM silver.transactions ORDER BY alert_datetime DESC LIMIT 25 "
    }
   ]
  }
 ]
}