services:
  postgres: # This is the name of the container, not a special keyword. Could be "db".
    image: postgres:16-alpine # Pinning version 16 ensures consistency across compose up and compose pull
    container_name: transact-db 
    restart: unless-stopped # Other options: always, on-failure
    environment: # Defines environment variables est in the container
      POSTGRES_USER: ${POSTGRES_USER} # With password, used to define root user. Default: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # This is the only variable required; the rest are optional
      POSTGRES_DB: ${POSTGRES_DB} # Name for default database. Default: POSTGRES_USER
    ports:
      - "${POSTGRES_PORT}:5432" # Host Port : Container Port
    volumes:
      - postgres_data:/var/lib/postgresql/data # Named volume postgres_data is mounted to contianer path /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  bento:
    image: ghcr.io/warpstreamlabs/bento:1.20.0
    container_name: transact-bento
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - stack.env
    ports:
      - "127.0.0.1:4195:4195"
    volumes:
      - ./config.yaml:/bento.yaml:ro
    command: ["-c", "/bento.yaml"]

volumes:
  postgres_data: # Create default local named volume called postgres_data if doesn't already exist
