apiVersion: 1

datasources:
  - name: PostgreSQL (transact-db)
    type: postgres
    access: proxy
    url: postgres:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
    isDefault: true
    editable: true
